#!/usr/bin/env bash
# PreToolUse (matcher: Edit|Write) — refuse edits/writes to secret-bearing or
# machine-generated files.
#
# This is NOT redundant with the settings.json deny list: path permission rules
# are only consulted for the Read and Edit tools, so a Write tool call to any of
# these paths is stopped here and nowhere else.
#
# Blocks with exit 2; the stderr message is fed back to Claude.
set -u

HOOKS_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd) || exit 0
# shellcheck source=./lib.sh
. "$HOOKS_DIR/lib.sh" 2>/dev/null || exit 0

HOOK_INPUT=$(cat)
hook_json_field tool_input.file_path
path="$HOOK_JSON_VALUE"
[ -n "$path" ] || exit 0

# A file path has no shell metacharacters to mangle, so the grep fallback is
# safe here: this hook stays fail-CLOSED even without python3/node.
rel=$(repo_rel_path "$path")
base=${rel##*/}

block() {
  printf 'BLOCKED by protect-secrets: %s\n' "$rel" >&2
  printf '%s\n' "$1" >&2
  exit 2
}

# --- .env family: .env.example is the one member that may be edited ----------
case "$base" in
  .env.example) ;;
  .env|.env.*|*.env)
    block "Environment files never enter the repo or an edit. If you need to document a variable, edit .env.example instead (values redacted). Real values are set by hand, locally or in the Vercel dashboard." ;;
esac

# --- directories that hold secrets or private plaintext ---------------------
case "$rel" in
  .vercel|.vercel/*)
    block "'.vercel/' is Vercel CLI local state (project + org ids, auth artifacts). It is gitignored and machine-owned — never edit it." ;;
  content-private|content-private/*)
    block "'content-private/' holds the UNENCRYPTED source content and is gitignored. Editing it from here risks leaking plaintext into a diff or a transcript. Edit it yourself, then re-run the encryption script." ;;
  .claude/settings.local.json)
    block "'.claude/settings.local.json' is machine-local and gitignored. Copy .claude/settings.local.json.example by hand and edit it yourself." ;;
esac

# --- key material -----------------------------------------------------------
case "$base" in
  *.pem|*.p12|*.pfx|*.key|id_rsa*|id_ed25519*)
    block "This looks like key material. Key and certificate files are never created or modified by an agent." ;;
esac

# --- machine-generated files that must be regenerated, not hand-edited ------
case "$base" in
  package-lock.json)
    block "Never hand-edit package-lock.json — it is regenerated by npm. Change package.json and run the appropriate npm command (e.g. 'npm install <pkg>' or 'npm ci'), then commit the resulting lockfile as-is." ;;
  next-env.d.ts)
    block "next-env.d.ts is generated and maintained by Next.js (it is rewritten by 'next dev' / 'next build' / 'next typegen'). Put your own ambient declarations in a separate .d.ts under types/ instead." ;;
esac

exit 0
