name: Lint CI
run-name: Lint CI ${{ github.ref_name }}
on: [push]
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run biome-ci
      - run: npm run lint
      - run: npm run nextlint
